### ISSUE TITLE
Blank page on nextcloud 

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/nextcloud_ynh#126]
Hi
After a fresh install I see a blank page on the nextcloud main page.
Error:
`[error] 6751#6751: *61038 FastCGI sent in stderr: "Access to the script '/var/www/nextcloud/index.php/' has been denied (see security.limit_extensions)" while reading response header from upstream,`

```
yunohost: 
  repo: stable
  version: 3.0.0.1
yunohost-admin: 
  repo: stable
  version: 3.0.0
moulinette: 
  repo: stable
  version: 3.0.0
ssowat: 
  repo: stable
  version: 3.0.0
```
